M48
; DRILL file {KiCad 7.0.9} date Thursday, February 19, 2026 at 09:42:25 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-19T21:42:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X101.62Y-48.14
T2
X51.22Y-64.64
X51.31Y-24.26
X110.07Y-24.21
X110.07Y-64.55
T0
M30
